SELECT * FROM      --쿼리 하나를 또다른 테이블처럼 쓸 쑤 있
(SELECT P.PATNAME NAME ,P.BIRTHDATE, O.OPDDATE OPDATE,COUNT(*)
FROM PATMST P, OPDACPT O
WHERE O.OPDDATE = '20240729'
AND O.PATID = P.PATID
GROUP BY P.PATNAME ,P.BIRTHDATE, O.OPDDATE)

WHERE CNT >1
