SELECT P.PATID "환자 아이디 ", P.PATNAME "환자이름 ",T.RSVDEPTCODE "진료과",T.RSVDATE "예약일",U.USRKORNAME "의사명"
FROM PATMST P, TOTRSVINFOS T, USRMST U
WHERE P.PATID = T. PATID
AND T.CHARGEDRID = U.USRID
AND T.RSVDATE >= '20240730'
order by t.rsvdeptcode
