SELECT PATNAME, CNT FROM (
SELECT P.PATNAME, P.PATID, COUNT(*) CNT
  FROM PATMST P, OPDACPT O
 WHERE P.PATID = O.PATID
   AND O.OPDDATE BETWEEN '20220101' AND '20220131'
   AND P.SEX = 'M'
GROUP BY P.PATNAME, P.PATID )

ORDER BY PATNAME
