SELECT P.PATID, O.OPDDATE, E.ORDERDATE, E.ORDERNAME, E.CLAS, DECODE(E.ORDERSTEPSTATE,0,'贸规',3,'立荐',4,'柳青') STATE, D.DEPTKORNAME, U.USRKORNAME
FROM PATMST P, OPDACPT O, ORDERINFOS E, DEPTCODES D, USRMST U
WHERE P.PATID ='24000034'
AND P.PATID = O.PATID
AND O.PATID = E.PATID
AND O.DEPTCODE = E.DEPTCODE
AND E.ORDERDATE = O.OPDDATE
AND E.ORDERDRDEPTCODE = D.DEPTCODE
AND E.ORDERDRID = U.USRID
ORDER BY CLAS




