SELECT P.PATID, O.OPDDATE, E.ORDERDATE, E.ORDERNAME, E.CLAS, DECODE(R.RSVACPTSTATE,0,'미접수',1,'접수','진행') ACPTSTATE, D.DEPTKORNAME, U.USRKORNAME
FROM PATMST P, OPDACPT O, ORDERINFOS E,REGISTINFOS R, DEPTCODES D, USRMST U
WHERE P.PATID ='24000034'
AND P.PATID = O.PATID
AND O.PATID = E.PATID
AND O.PATID = R.PATID
AND O.DEPTCODE = E.DEPTCODE
AND E.ORDERDATE = O.OPDDATE
AND E.DEPTCODE = R.DEPTCODE
AND E.SLIPNO = R.SLIPNO
AND E.ORDERDRDEPTCODE = D.DEPTCODE
AND E.ORDERDRID = U.USRID
ORDER BY CLAS

