--2. 원무접수일 / 처방일 / 환자명 / 처방명 / 구분 (CLAS) / 진료지원 진행상태 (RSVACPTSTATE) / 진료과명 / 의사명 /
SELECT P.PATID "환자명", O.OPDDATE "원무접수일", E.ORDERDATE "처방일", E.ORDERNAME "처방명", E.CLAS "구분", DECODE(R.RSVACPTSTATE,0,'미접수',1,'접수','진행') "진료지원 진행상태", D.DEPTKORNAME "진료과명", U.USRKORNAME "의사명"
FROM PATMST P, OPDACPT O, ORDERINFOS E,REGISTINFOS R, DEPTCODES D, USRMST U
WHERE P.PATID ='24000034'
AND P.PATID = O.PATID
AND O.PATID = E.PATID
AND O.PATID = R.PATID
AND O.DEPTCODE = E.DEPTCODE
AND E.ORDERDATE = O.OPDDATE
AND E.ORDERDATE = R.ORDERDATE
AND E.DEPTCODE = R.DEPTCODE
AND E.SLIPSEQ = R.SLIPSEQ
AND E.SLIPNO = R.SLIPNO
AND E.ORDERDRDEPTCODE = D.DEPTCODE
AND E.ORDERDRID = U.USRID
ORDER BY E.CLAS,O.OPDDATE,E.ORDERDATE

