 SELECT O.PATID,  P.PATNAME,  P.SEX,    O.DEPTCODE, D.DEPTABBRNAME,      U.USRKORNAME,    B.BASICNAME, B2.BASICNAME BASICSUBNAME,--별명 정해줌'
        O.OPDTIME ADD1, O.RSVFLAG ADD2, -- 컬럼명
        DECODE(O.ACPTSTAT,0,'신환',1,'초진',2,'재진') ADD3, --데이터를 비교하고 조건에 따라 값을 반환
        O.OPDCNT, O.RCVFLAG, O.CLNCCNFRMFLAG,
        P.BIRTHDATE,
        NVL((SELECT MIN(ORDERSTEPSTATE) FROM ORDERINFOS I  -- subrcb -1 을 찾는 쿼리
        WHERE O.PATID = I.PATID
       -- AND O.OPDCNT = I.OPDCNT
        AND CLAS > 0), -1) SUBRCV,
        P.PATID || DECODE(TRIM(P.PATGRADE), NULL, NULL, '-' || P.PATGRADE) PATID2 , 1 ORDERBYFLAG , '' AGE, P.CENT, P.PRSNIDPRE --쿼리 합쳐줌
   FROM OPDACPT O, PATMST P, USRMST U, BASICCODES B, BASICCODES B2, DEPTCODES D
  WHERE O.PATID = P.PATID
    AND O.CHRGDRID = U.USRID
    AND O.CLSSCODE = B.BASICCODE
    AND O.CLSSSUBCODE = B2.BASICCODE
    AND B.BASICSTAT = 1
    AND B2.BASICSTAT = 2
    AND O.IPDFLAG = 0
    AND P.NONUSEFLAG = 0
    AND O.ACPTCANCELFLAG = 0
    AND O.DEPTCODE = D.DEPTCODE
    AND O.OPDDATE BETWEEN '20240725' AND '20240725'
    AND O.DEPTCODE <> 'SO'  AND O.CLNCCNFRMFLAG = 0
  ORDER BY O.OPDTIME
;
